import type { NextPage } from "next";
import Head from "next/head";
import Button from "../components/Button";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Remote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Remote</h1>
        <Button />
      </main>

      <footer className={styles.footer}>
        <p>NovaFutur</p>
      </footer>
    </div>
  );
};

export default Home;
